### PR TITLE
Add author key on hello-world post

### PR DESCRIPTION
**Pull request by SpyHoodle**
- also added more text in short:
- also removed date, read issue #33 for info

### CODE REVIEW

**Comment by A-da-m** [comment]
@abcdan Issue #33 is where we will be adding support for the date key.

**Comment by SpyHoodle** [comment]
Have you read #33 ?
This is on the todo list already and will probably be done by adam.
I say comment on #33 with the suggestion.
Also unix timestamp will break in future.

**Comment by abcdan** [comment]
> Have you read #33 ?
> This is on the todo list already and will probably be done by adam.
> I say comment on #33 with the suggestion.
> Also unix timestamp will break in future.

Yeh, but we'll replace the unix with a database type stuff (maybe get last file edit) in the future so it will work for now.

**Comment by SpyHoodle** [comment]
Temporary measure. Anyway, merge.

**Comment by abcdan** [comment]
Can you first add the date key?

**Comment by SpyHoodle** [comment]
Adam is doing this in issue #33. I see no reason not to merge.
Also depends when adam starts doing it.

**Pull request merged**
