### PR TITLE
Fixing issue #17

### PR DESCRIPTION
**Pull request by anishanne**
This is a PR to fix issue #17 

1) Changed buttons to links.  `<a>` vs `<button>`
2) Discord invite opens now opens in a new tab. `target="_BLANK"`

### CODE REVIEW

**Comment by taneltm** [comment]
Should be `_blank` not `_BLANK`.

**Comment by abcdan** [comment]
I agree with Tanel on this one, will close for now. :sparkles:

**Comment by anishanne** [comment]
Typo, my bad. Should I fix it or?

**Comment by abcdan** [comment]
Fix it and make a new PR

**Pull request closed without merging**
